[versions]
lombok = "1.18.46"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
spring-restdocs = "4.0.0"
asciidoctor = "4.0.5"
hibernate = "7.4.1.Final"
spotless = "8.0.0"
commons-validator = "1.11.0"
jts-core = "1.19.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }
jts-core = { module = "org.locationtech.jts:jts-core", version.ref="jts-core"}
hibernate-jpamodelgen = { module = "org.hibernate.orm:hibernate-jpamodelgen", version.ref = "hibernate"}

spring-boot-starter-actuator-test = { module = "org.springframework.boot:spring-boot-starter-actuator-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-restdocs = { module = "org.springframework.boot:spring-boot-starter-restdocs" }
spring-restdocs-mockmvc = { module = "org.springframework.restdocs:spring-restdocs-mockmvc", version.ref = "spring-restdocs" }
spring-restdocs-asciidoctor = { module = "org.springframework.restdocs:spring-restdocs-asciidoctor", version.ref = "spring-restdocs" }

junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
asciidoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }